# Plugin von iTzDxnisHD

# Discord Link: https://discord.gg/tUh3EyP

# JoinMessage
JoinMessage: "$name hat den Server betreten."

# QuitMessage
QuitMessage: "$name hat den Server verlassen."

# Bugs? sende sie mir per discord
